# Generated by Django 6.0.7 on 2026-08-04 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='cinema',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='format',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='movie_poster',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='movie_title',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='show_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 4, 15, 15, 22, 436491, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='show_time',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='upcoming', max_length=50),
        ),
    ]
