# Generated by Django 6.0.7 on 2026-08-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_booking_date_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Watchlist',
                ),
            ],
            database_operations=[],
        ),
    ]
